test:
  adapter: postgresql
  encoding: unicode
  database: lcboapi_test
  template: template_postgis

development:
  adapter: postgresql
  encoding: unicode
  database: lcboapi_development
  template: template_postgis

production:
  adapter: postgresql
  encoding: unicode
  database: lcboapi
  pool: 5
