:test:        "postgres://lcboapi_test?template=template_postgis&encoding=unicode"
:development: "postgres://lcboapi_development?template=template_postgis&encoding=unicode"
:production:  "postgres://lcboapi?encoding=unicode"
