---
-
  :name: Datasets
  :docs:
    -
      :title: Datasets
      :route: /datasets
    -
      :title: Dataset
      :route: /datasets/:dataset_id

-
  :name: Products
  :docs:
    -
      :title: Search Products
      :route: /products
    -
      :title: Product Details
      :route: /products/:product_id
    -
      :title: Search Products at Store
      :route: /stores/:store_id/products

-
  :name: Stores
  :docs:
    -
      :title: Stores with Product
      :route: /products/:product_id/stores
    -
      :title: Search Stores
      :route: /stores
    -
      :title: Store Details
      :route: /stores/:store_id

-
  :name: Inventories
  :docs:
    -
      :title: Search Inventories
      :route: /inventories
    -
      :title: Inventory Details
      :route: /stores/:store_id/products/:product_id/inventory
    -
      :title: Product Inventories
      :route: /products/:product_id/inventories

-
  :name: History
  :docs:
    -
      :title: Product History
      :route: /products/:product_id/history
    -
      :title: Store History
      :route: /stores/:store_id/history
    -
      :title: Inventory History
      :route: /stores/:store_id/products/:product_id/history
