---
development:
  s3_access_key: 1A5G7BC0QWX3VPE1HPR2
  s3_secret_key: ScIfPtySDKHJ3a0pCFxZyqHpJL3nir2a0z7RHudO
  s3_bucket: static.lcboapi.com
  lcbo_user_agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
  secret_key_base: 813be4d903d5ca2dc378befc38c17aca14473706c9c92ed0a5fc737306a1caaea857ca947eaedef8e310ebba724e55499f3dba479840b0eabf66133dedcd6813
  admin_username: heycarsten
  admin_password: password

test:
  s3_access_key: 1A5G7BC0QWX3VPE1HPR2
  s3_secret_key: ScIfPtySDKHJ3a0pCFxZyqHpJL3nir2a0z7RHudO
  s3_bucket: static.lcboapi.com
  lcbo_user_agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
  secret_key_base: 813be4d903d5ca2dc378befc38c17aca14473706c9c92ed0a5fc737306a1caaea857ca947eaedef8e310ebba724e55499f3dba479840b0eabf66133dedcd6813
  admin_username: heycarsten
  admin_password: password
